### ISSUE TITLE
Example how to use the mesh2pcd parser

### ISSUE THREAD

**Issue by ttsesm** [Xelawk/mesh_utils#1]
Hi @Xelawk,

I followed the discussion in this issue [here](https://github.com/isl-org/Open3D/issues/2483) and I found your repository. I am interested to create a point cloud from a textured obj mesh.

Initially I used the following code:
```
pcd1 = o3d.geometry.PointCloud(mesh1.vertices)
pcd1.normals = mesh1.vertex_normals
pcd1.colors = mesh1.vertex_colors
```

but since the `mesh1` has the color information as uv texture coordinates the last command failed to work. Thus, I was wondering whether you parser can do that and if yes, whether it would be easy for you to provide an example.

Thanks.

**Comment by Xelawk** [comment]
> Hi @Xelawk,
> 
> I followed the discussion in this issue [here](https://github.com/isl-org/Open3D/issues/2483) and I found your repository. I am interested to create a point cloud from a textured obj mesh.
> 
> Initially I used the following code:
> 
> ```
> pcd1 = o3d.geometry.PointCloud(mesh1.vertices)
> pcd1.normals = mesh1.vertex_normals
> pcd1.colors = mesh1.vertex_colors
> ```
> 
> but since the `mesh1` has the color information as uv texture coordinates the last command failed to work. Thus, I was wandering whether you parser can do that and if yes, whether it would be easy for you to provide an example.
> 
> Thanks.

Hi @ttsesm . The repo is the work I did long time ago. But I very will to provide you an example for helping you better using the code. To make it, do you have any example of mesh file (obj etc.) with texture file (jpg, png any way).If yes, please just send it to me and I will update an example when I have time.

**Comment by ttsesm** [comment]
> > Hi @Xelawk,
> > I followed the discussion in this issue [here](https://github.com/isl-org/Open3D/issues/2483) and I found your repository. I am interested to create a point cloud from a textured obj mesh.
> > Initially I used the following code:
> > ```
> > pcd1 = o3d.geometry.PointCloud(mesh1.vertices)
> > pcd1.normals = mesh1.vertex_normals
> > pcd1.colors = mesh1.vertex_colors
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but since the `mesh1` has the color information as uv texture coordinates the last command failed to work. Thus, I was wondering whether you parser can do that and if yes, whether it would be easy for you to provide an example.
> > Thanks.
> 
> Hi @ttsesm . The repo is the work I did long time ago. But I very will to provide you an example for helping you better using the code. To make it, do you have any example of mesh file (obj etc.) with texture file (jpg, png any way).If yes, please just send it to me and I will update an example when I have time.

The attached file should do the job. You can load it as: 

`mesh = o3d.io.read_triangle_mesh("./Tombstone1.obj", enable_post_processing=True, print_progress=True)`

In principle, I do not want to sample but rather port the mesh directly to a point cloud as it is (i.e. keeping the color values). I guess this could be done by interpolating the uv coordinates from the mesh per vertex and read the color value inside the texture image to get the color?


[data.zip](https://github.com/Xelawk/mesh_utils/files/7626537/data.zip)

**Comment by Xelawk** [comment]
> > > Hi @Xelawk,
> > > I followed the discussion in this issue [here](https://github.com/isl-org/Open3D/issues/2483) and I found your repository. I am interested to create a point cloud from a textured obj mesh.
> > > Initially I used the following code:
> > > ```
> > > pcd1 = o3d.geometry.PointCloud(mesh1.vertices)
> > > pcd1.normals = mesh1.vertex_normals
> > > pcd1.colors = mesh1.vertex_colors
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > but since the `mesh1` has the color information as uv texture coordinates the last command failed to work. Thus, I was wondering whether you parser can do that and if yes, whether it would be easy for you to provide an example.
> > > Thanks.
> > 
> > 
> > Hi @ttsesm . The repo is the work I did long time ago. But I very will to provide you an example for helping you better using the code. To make it, do you have any example of mesh file (obj etc.) with texture file (jpg, png any way).If yes, please just send it to me and I will update an example when I have time.
> 
> The attached file should do the job. You can load it as:
> 
> `mesh = o3d.io.read_triangle_mesh("./Tombstone1.obj", enable_post_processing=True, print_progress=True)`
> 
> In principle, I do not want to sample but rather port the mesh directly to a point cloud as it is (i.e. keeping the color values). I guess this could be done by interpolating the uv coordinates from the mesh per vertex and read the color value inside the texture image to get the color?
> 
> [data.zip](https://github.com/Xelawk/mesh_utils/files/7626537/data.zip)

Hi @ttsesm , the repo has been update, just try it. Maybe it could meet your demand :)

**Comment by Xelawk** [comment]
It must be noted that the whole project code is still very rough because there is no time for me refactoring carefully. For figure it out quickly, a test sample is specially added to make pre-processing of an obj file to an acceptable self-defined file format, then applying my code to files generated for sampling pointcloud with RGB values

**Comment by ttsesm** [comment]
Thanks @Xelawk. It seems to do the job, the texture quality is not the best but this is expected. 

Btw, [here](https://github.com/marcomusy/vedo/issues/548) someone can find another solution by using the vedo lib. It is not exactly point cloud sampling but rather just 1:1 mesh to pcd with color solution.

**Comment by Xelawk** [comment]
> 

Got it, btw, the quality of resolution depends on the num of sample points you set and texture image quality. Have a try.

**Comment by ttsesm** [comment]
> Got it, btw, the quality of resolution depends on the num of sample points you set and texture image quality. Have a try.

Well not necessarily, I think it has to do more with the interpolation of the points to the UV coordinates (possibly a bilinear interpolation would give a better result).

For example you can see the output of the pcd sampling with 1000000 points, which is not the best:
![image](https://user-images.githubusercontent.com/10189018/144408965-856d1072-d1f0-4f81-8840-8abbdffa04a1.png)

while the original one texture on the mesh is:
![image](https://user-images.githubusercontent.com/10189018/144409562-e658861d-b044-446e-96a2-4471a2e15cfd.png)

**Comment by Xelawk** [comment]
> > Got it, btw, the quality of resolution depends on the num of sample points you set and texture image quality. Have a try.
> 
> Well not necessarily, I think it has to do more with the interpolation of the points to the UV coordinates (possibly a bilinear interpolation would give a better result).
> 
> For example you can see the output of the pcd sampling with 1000000 points, which is not the best: ![image](https://user-images.githubusercontent.com/10189018/144408965-856d1072-d1f0-4f81-8840-8abbdffa04a1.png)
> 
> while the original one texture on the mesh is: ![image](https://user-images.githubusercontent.com/10189018/144409562-e658861d-b044-446e-96a2-4471a2e15cfd.png)

It may be that the UV coordinates are not completely calculated correctly. This job was originally adapted to the private data. I just simply make transformation from obj, which may not be matched correctly.
